# Generated by Django 5.1.4 on 2025-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_city_options_remove_event_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
